### ISSUE TITLE
status ?

### ISSUE THREAD

**Issue by setop** [robinheghan/elm-code-gen-experiments#1]
Hi @robinheghan,

Very interesting content.

Do you know if any of these suggestion you made here and in [this article](https://dev.to/robinheghan/improving-elm-s-compiler-output-5e1h) has been implemented, either in the main repo, a PR or a fork ?

Thanks

**Comment by robinheghan** [comment]
Hi!

`elm-optimize-level-2` was inspired by those articles, so I'd look into that: https://discourse.elm-lang.org/t/announcing-elm-optimize-level-2/6192
